remote_theme: mmistakes/minimal-mistakes@4.17.2
plugins:
- jekyll-include-cache

locale: "en-US"
title: "My Academic Webpage"
name: "Anthony Albert Marcozzi"
description: "A personal academic webpage for CS 501"
url: "https://amarcozzi.github.io"
search: true
logo: "/assets/images/author_avatar.jpg"
author:
	name: "Anthony Albert Marcozzi"
	avatar: "/assets/images/author_avatar.jpg"
	bio: "I am a masters student at the University of Montana"
	location: "Missoula, MT"

defaults:
	# _pages
	- scope:
		path: ""
		type: pages
	values:
		layout: single
		author_profile: true
	# _posts
	- scope:
		path: ""
		type: posts
	values:
		layout: single
		author_profile: true
		read_time: true
		comments: true
		share: true
		related: true
	paginate: 5
	paginate_path: /page:num/

include:
	- _pages 
